name = "repo-analyzer-api"
main = "src/worker.js"
compatibility_date = "2023-12-01"
workers_dev = true

[vars]
AWS_REGION = "eu-central-1"
AWS_S3_BUCKET = "repo-analyzer"

[env.production]
routes = [
  { pattern = "api.analyzer.gokhanozturk.io", custom_domain = true }
]

[env.production.vars]
NODE_ENV = "production"

[env.development]
workers_dev = true

[env.development.vars]
NODE_ENV = "development"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "repo-analyzer"
preview_bucket_name = "repo-analyzer-dev"

[build]
command = "cargo build --release --target wasm32-wasi && wasm-bindgen target/wasm32-wasi/release/repo-analyzer-api.wasm --out-dir ./build"